### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by M-Fasciano** [Wufe/react-particles-js#117]
Hi Simone, 

I'm using React Particles in my portfolio and works great, thank you.

The only issue I've found is when I run Lighthouse from Google.

The error says **Does not use passive listeners to improve scrolling performance**.

Hope you can help.

**Comment by matteobruni** [comment]
Hi @M-Fasciano,

Thanks for the report, I've opened an issue in tsParticles about this warning and it will be released a fix in the next version this weekend.

**Comment by M-Fasciano** [comment]
> Hi @M-Fasciano,
> 
> Thanks for the report, I've opened an issue in tsParticles about this warning and it will be released a fix in the next version this weekend.

Hi @matteobruni ,

I've tested your demo in chrome and still can see the issue I've mentioned above.

Thank you
Michele

**Comment by matteobruni** [comment]
Hi @M-Fasciano, do you use any additional extension?

I've double checked now and chrome doesn't gives any warning like that

**Comment by M-Fasciano** [comment]
> Hi @M-Fasciano, do you use any additional extension?
> 
> I've double checked now and chrome doesn't gives any warning like that

Hi @matteobruni,

Maybe I wasn't clear enough when I've opened the issue. Basically, if you open Chrome inspector there is a tab called **Audits**, if you press it then you will see another button "**Generate report**". Once the report is done you will see the error under the best practice section. I've attached a screenshot. Let me know if you need more information. 

<img width="1439" alt="Screenshot 2020-04-25 at 11 29 04" src="https://user-images.githubusercontent.com/20194640/80277737-00f85c80-86e9-11ea-806a-a7ff4f7ab0be.png">

This is what google devs suggest as a fix. https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools

Thank you 
Michele

**Comment by matteobruni** [comment]
Ok I've found the report you're talking about. I've checked my demo site and that practice is ok, when did you checked? I've updated the demo website tonight (CEST TZ).

I've seen your GH page repository and it uses `react-particles-js` 3.0.3, can you try upgrade to 3.1.0 and installing `tsParticles` version to 1.13.0 to override the 1.12.11 dependency? 1.13.0 version should fix that issue.

**Comment by M-Fasciano** [comment]
> Ok I've found the report you're talking about. I've checked my demo site and that practice is ok, when did you checked? I've updated the demo website tonight (CEST TZ).
> 
> I've seen your GH page repository and it uses `react-particles-js` 3.0.3, can you try upgrade to 3.1.0 and installing `tsParticles` version to 1.13.0 to override the 1.12.11 dependency? 1.13.0 version should fix that issue.

Hi @matteobruni,

I've just generated a report of your demo and this is the result. As you can see from the screenshot the issue is still there. 

<img width="1436" alt="Screenshot 2020-04-25 at 12 39 51" src="https://user-images.githubusercontent.com/20194640/80278941-40777680-86f2-11ea-9720-6e0db667c825.png">

**Comment by matteobruni** [comment]
I think it's an extension you have installed that gives the issue.

I'll attach you screenshots of my Chrome, it's a clean install because I don't use it.

![Schermata 2020-04-25 alle 13 47 05](https://user-images.githubusercontent.com/176620/80279055-5ccbe100-86fb-11ea-9d85-333f6345a5d9.png)
![Schermata 2020-04-25 alle 13 46 19](https://user-images.githubusercontent.com/176620/80279056-5dfd0e00-86fb-11ea-8075-ed004079e75d.png)

Can you try checking if Chrome gives you the warning with all extensions disabled?

**Comment by M-Fasciano** [comment]
> Ok I've found the report you're talking about. I've checked my demo site and that practice is ok, when did you checked? I've updated the demo website tonight (CEST TZ).
> 
> I've seen your GH page repository and it uses `react-particles-js` 3.0.3, can you try upgrade to 3.1.0 and installing `tsParticles` version to 1.13.0 to override the 1.12.11 dependency? 1.13.0 version should fix that issue.

Hi @matteobruni,

I'll try to do what you have suggested and let you know.

**Comment by M-Fasciano** [comment]
Hi @matteobruni,

I've updated Particles.js and installed tsParticles, tested in chrome incognito and everything seems to work fine. The error is not related to Particles.js but to a chrome extension called [ng-inspector](https://github.com/rev087/ng-inspector). Thanks for your time  :pray:
